# -*- coding: utf-8 -*-
"""Calculo-nota-mackenzie.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q3gBU3eOuS6pryfRF_KuSpwNsPR4hceh

## CALCULO DA MÉDIA SEMESTRAL COM/SEM A P2(Prova Intermediária 2)
### E cálculo nota mínima na PROVA FINAL
"""

import math
def notaComP2():
    p1 = float(input('Avaliação Intermediária 1 (P1): '))
    p2 = float(input('Avaliação Intermediária 2 (P2): '))
    N2 = float(input('Nota do Moodle (N2): '))
    Partic = float(input('Nota de participação (partic): '))
    
    while Partic > 1:
        print('Nota de participação não pode ser superior a 1')
        print('Digite a nota de 0.0 até 1.0')
        Partic = float(input('Nota de participação: '))
        
    NS = ((p1 + p2) * 0.3) + (N2 * 0.4) + Partic   
    if NS > 10:
      print(f'\nNota semestral será: 10')
    else:
      print(f'\nNota semestral será: %.1f' % NS) 
    
    
    deuMedia = 6 - NS
    
    if NS < 6:
        print("\nNão é possível fechar o semestre sem Prova Final!")
        falta = (12 - NS)
        print('Nota mínima na Prova Final (P3) precisa ser: %.2f' % falta)
    else:
        print('\nSua nota atinge a média para passar!')        
        resp = input("\n\nVocê quer calcular outra nota? Digite 1 para SIM ou 2 para NÃO: ")
        if resp == "1":
          main("0")

def notaSemP2():
    p1 = float(input('Avaliação Intermediária 1 (P1): '))
    qseNI = (p1 / 2) * 0.6
    N2 = float(input('Nota do Moodle (N2): '))
    NI2 = N2 * 0.4
    Partic = float(input('Nota de participação (partic): '))
    
    while Partic > 1:
        print('Nota de participação não pode ser superior a 1')
        print('Digite a nota de 0.0 até 1.0')
        Partic = float(input('Nota de participação: '))
        
    NS = (((qseNI + NI2)) + Partic)
    print(f'\nSua P1 vai somar {qseNI} na sua nota semestral')
    print(f'As atividades do Moodle vão somar %.2f na sua nota semestral' % NI2)
    print(f'Nota semestral sem Avaliação Intermediária 2 será: %.1f' % NS)
    
    deuMedia = 6 - NS
    
    if NS < 6:
        falta = deuMedia / 0.3
        if falta > 10:
            print("\nNão é possível fechar o semestre só com a Avaliação Intermediária 2!")
        else:
            print('\nNota mínima na Avaliação Intermediária 2 (P2) precisa ser: %.2f' % falta)
    else:
        print('\nSua nota atinge a média para passar!')
    res = input("\n\nVocê quer calcular outra nota? Digite 1 para SIM ou 2 para NÃO: ")
    if res == "1":
      main("0")

def main(resp):
    resposta = resp
    
    while resposta != "1" and resposta != "2":
      print("Você já fez a Avaliação Intermediária 2?")
      resposta = input("Digite 1 para SIM ou 2 para NÃO: ")
        
    if resposta == "1":
            notaComP2()
    elif resposta == "2":
            notaSemP2()

main(0)

